download_path_min_len = 88
port = '9104'
network_address = '127.0.0.1'
debug = true
pp_list_dir = "./peers"
account_dir = "./accounts"
storehouse_path = "./storage"
download_path = "./download"
p2p_address = 'stsds1ttpyyh9p7udalhwcz7sh5f5zfzuhpm0h3c0hzc'
p2p_password = 'aaa'
wallet_address = 'st172v4u8ysfgaphjs8uyy0svvc6d6tzl6gp07kn4'
wallet_password = 'aaa'
auto_run = true
internal = false
is_wallet = true
is_limit_download_speed = false
limit_download_speed = 100
is_limit_upload_speed = false
limit_upload_speed = 100
chain_id = 'testchain'
stratos_chain_url = 'http://127.0.0.1:1317'
rest_port = '9204'
internal_port = '9304'
rpc_port = '9404'
metrics_port = '9604'
traffic_log_interval = 10
max_connection = 1000

[monitor]
tls = false
cert = ''
key = ''
port = '9504'

[version]
app_ver = 8
min_app_ver = 8
show = 'v0.8.1'

[[sp_list]]
p2p_address = ""
p2p_public_key = ""
network_address = "0.0.0.0:8888"
